# версия yml-файла
version: "3.7"

services:
  backend:
    container_name: 'backend'
    build:
      context: backend
      dockerfile: Dockerfile
    # пробросить в контейнер env-переменные
    env_file: backend/.env
    image: kupi_podari_daj_backend:latest
    restart: unless-stopped
#    entrypoint: 'sleep infinity'
    ports:
      - '3000:3000'
    # контейнер с бэкендом стартует только после запуска контейнера с постгресом
    depends_on:
      - postgres

  postgres:
    container_name: 'postgres'
    image: postgres:12.12-alpine
    restart: always
    env_file: ./backend/.env.postgres

  frontend:
    container_name: 'frontend'
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - '81:81'